"""The llama.cpp AI Task integration."""

from __future__ import annotations

from dataclasses import dataclass

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import CONF_API_KEY, CONF_URL, Platform
from homeassistant.core import HomeAssistant
from homeassistant.exceptions import ConfigEntryAuthFailed, ConfigEntryNotReady
from homeassistant.helpers import device_registry as dr, entity_registry as er
from homeassistant.helpers.aiohttp_client import async_get_clientsession

from .client import (
    LlamaCppAuthError,
    LlamaCppClient,
    LlamaCppError,
    LlamaCppServerInfo,
    normalize_base_url,
)
from .const import CONF_MODEL, DEFAULT_AI_TASK_NAME, DOMAIN, LOGGER
from .helpers import model_name_to_title

PLATFORMS: tuple[Platform, ...] = (Platform.AI_TASK,)
CONFIG_ENTRY_VERSION = 2


@dataclass(slots=True)
class LlamaCppRuntimeData:
    """Data shared by all entities of a config entry."""

    client: LlamaCppClient
    info: LlamaCppServerInfo
    model: str | None


type LlamaCppConfigEntry = ConfigEntry[LlamaCppRuntimeData]


def _migration_title(subentry) -> str:
    """Return the VERSION 2 title for a subentry.

    Only the known legacy default title is converted to a model-derived default.
    Any other title is treated as user-owned and must be preserved.
    """
    if subentry.title != DEFAULT_AI_TASK_NAME:
        return subentry.title
    model = subentry.data.get(CONF_MODEL)
    if model:
        return model_name_to_title(str(model))
    return subentry.title


def _migrate_v1_registry_entries(
    hass: HomeAssistant,
    entry: LlamaCppConfigEntry,
    migrated_titles: dict[str, str],
) -> None:
    """Migrate legacy autogenerated entity IDs and custom service devices."""
    entity_registry = er.async_get(hass)
    legacy_entity_base = f"{Platform.AI_TASK}.{DOMAIN}"

    for entity in er.async_entries_for_config_entry(entity_registry, entry.entry_id):
        if entity.platform != DOMAIN:
            continue

        changes: dict[str, object] = {}
        if entity.device_id is not None:
            changes["device_id"] = None

        is_legacy_entity_id = (
            entity.entity_id == legacy_entity_base
            or entity.entity_id.startswith(f"{legacy_entity_base}_")
        )
        if is_legacy_entity_id:
            subentry_id = entity.config_subentry_id or entity.unique_id
            if title := migrated_titles.get(subentry_id):
                changes["new_entity_id"] = (
                    entity_registry.async_get_available_entity_id(
                        Platform.AI_TASK, title
                    )
                )

        if changes:
            entity_registry.async_update_entity(entity.entity_id, **changes)

    device_registry = dr.async_get(hass)
    for device in dr.async_entries_for_config_entry(device_registry, entry.entry_id):
        if any(identifier[0] == DOMAIN for identifier in device.identifiers):
            device_registry.async_remove_device(device.id)


async def async_migrate_entry(
    hass: HomeAssistant, entry: LlamaCppConfigEntry
) -> bool:
    """Migrate persistent config and registry state to the current version."""
    LOGGER.debug(
        "Migrating config entry %s from version %s", entry.entry_id, entry.version
    )

    if entry.version > CONFIG_ENTRY_VERSION:
        LOGGER.error(
            "Cannot migrate config entry %s from future version %s",
            entry.entry_id,
            entry.version,
        )
        return False

    if entry.version == 1:
        data = dict(entry.data)
        if isinstance((url := data.get(CONF_URL)), str):
            data[CONF_URL] = normalize_base_url(url)

        # Older releases sometimes stored a null/blank key. Keep a real key now
        # that authentication is optional again, but remove meaningless values.
        if not data.get(CONF_API_KEY):
            data.pop(CONF_API_KEY, None)

        migrated_titles: dict[str, str] = {}
        for subentry in tuple(entry.subentries.values()):
            title = _migration_title(subentry)
            migrated_titles[subentry.subentry_id] = title
            if title != subentry.title:
                hass.config_entries.async_update_subentry(
                    entry, subentry, title=title
                )

        _migrate_v1_registry_entries(hass, entry, migrated_titles)
        hass.config_entries.async_update_entry(
            entry,
            data=data,
            version=CONFIG_ENTRY_VERSION,
        )

    return True


async def async_setup_entry(hass: HomeAssistant, entry: LlamaCppConfigEntry) -> bool:
    """Set up llama.cpp AI Task from a config entry."""
    client = LlamaCppClient(
        async_get_clientsession(hass),
        entry.data[CONF_URL],
        entry.data.get(CONF_API_KEY),
    )

    try:
        info = await client.async_detect_server_info()
    except LlamaCppAuthError as err:
        # Authentication failures are persistent until credentials change, so
        # trigger Home Assistant's reauthentication flow instead of retrying.
        raise ConfigEntryAuthFailed(str(err)) from err
    except LlamaCppError as err:
        # Connection/model startup failures may be transient.
        raise ConfigEntryNotReady(str(err)) from err

    await client.async_list_models()
    model = client.default_model or info.model_name

    LOGGER.debug(
        "Connected to llama.cpp %s serving %s (n_ctx=%s, modalities=%s, model=%s)",
        info.build_info,
        info.model_name,
        info.n_ctx,
        info.modalities,
        model,
    )

    entry.runtime_data = LlamaCppRuntimeData(client=client, info=info, model=model)

    # Persistent title/URL/registry migration belongs in async_migrate_entry.
    # Keeping setup mutation-free avoids update-listener/reload ordering hazards.
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    entry.async_on_unload(entry.add_update_listener(async_update_entry))

    return True


async def async_update_entry(hass: HomeAssistant, entry: LlamaCppConfigEntry) -> None:
    """Reload the entry when options or subentries change."""
    await hass.config_entries.async_reload(entry.entry_id)


async def async_unload_entry(hass: HomeAssistant, entry: LlamaCppConfigEntry) -> bool:
    """Unload a config entry."""
    return await hass.config_entries.async_unload_platforms(entry, PLATFORMS)
