"""The llama.cpp AI Task integration."""

from __future__ import annotations

from dataclasses import dataclass

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import CONF_URL, Platform
from homeassistant.core import HomeAssistant
from homeassistant.exceptions import ConfigEntryNotReady
from homeassistant.helpers import device_registry as dr, entity_registry as er
from homeassistant.helpers.aiohttp_client import async_get_clientsession

from .client import LlamaCppClient, LlamaCppError, LlamaCppServerInfo
from .const import CONF_MODEL, DOMAIN, LOGGER
from .helpers import model_name_to_title

PLATFORMS: tuple[Platform, ...] = (Platform.AI_TASK,)


@dataclass(slots=True)
class LlamaCppRuntimeData:
    """Data shared by all entities of a config entry."""

    client: LlamaCppClient
    info: LlamaCppServerInfo
    model: str | None


type LlamaCppConfigEntry = ConfigEntry[LlamaCppRuntimeData]


def _model_for_subentry(entry: LlamaCppConfigEntry, subentry_id: str) -> str | None:
    """Return the model that should identify one AI Task subentry."""
    subentry = entry.subentries.get(subentry_id)
    if subentry is None:
        return None
    value = subentry.data.get(CONF_MODEL) or entry.runtime_data.model or subentry.title
    return str(value) if value else None


def _migrate_legacy_registry_entries(
    hass: HomeAssistant, entry: LlamaCppConfigEntry
) -> None:
    """Apply model-based naming and remove legacy custom service devices.

    Older versions used a generic subentry title and standalone entity IDs such as
    ``ai_task.llama_cpp_ai_task_<subentry id>``. Home Assistant Core's llama.cpp
    integration names each subentry from its model, so migrate only those known
    autogenerated IDs. User-renamed entity IDs are left untouched.
    """
    for subentry in tuple(entry.subentries.values()):
        if not (model := _model_for_subentry(entry, subentry.subentry_id)):
            continue
        title = model_name_to_title(model)
        if subentry.title != title:
            hass.config_entries.async_update_subentry(entry, subentry, title=title)

    entity_registry = er.async_get(hass)
    legacy_entity_base = f"{Platform.AI_TASK}.{DOMAIN}"
    for entity in er.async_entries_for_config_entry(entity_registry, entry.entry_id):
        if entity.platform != DOMAIN:
            continue

        changes: dict[str, object] = {}
        if entity.device_id is not None:
            changes["device_id"] = None

        is_legacy_entity_id = entity.entity_id == legacy_entity_base or entity.entity_id.startswith(
            f"{legacy_entity_base}_"
        )
        if is_legacy_entity_id:
            subentry_id = entity.config_subentry_id or entity.unique_id
            if model := _model_for_subentry(entry, subentry_id):
                title = model_name_to_title(model)
                changes["new_entity_id"] = entity_registry.async_get_available_entity_id(
                    Platform.AI_TASK, title
                )

        if changes:
            entity_registry.async_update_entity(entity.entity_id, **changes)

    device_registry = dr.async_get(hass)
    for device in dr.async_entries_for_config_entry(device_registry, entry.entry_id):
        if any(identifier[0] == DOMAIN for identifier in device.identifiers):
            device_registry.async_remove_device(device.id)


async def async_setup_entry(hass: HomeAssistant, entry: LlamaCppConfigEntry) -> bool:
    """Set up llama.cpp AI Task from a config entry."""
    client = LlamaCppClient(
        async_get_clientsession(hass),
        entry.data[CONF_URL],
    )

    try:
        info = await client.async_detect_server_info()
    except LlamaCppError as err:
        # The server may simply still be loading the model.
        raise ConfigEntryNotReady(str(err)) from err

    models = await client.async_list_models()
    model = client.default_model or (models[0] if models else info.model_name)

    LOGGER.debug(
        "Connected to llama.cpp %s serving %s (n_ctx=%s, modalities=%s, model=%s)",
        info.build_info,
        info.model_name,
        info.n_ctx,
        info.modalities,
        model,
    )

    entry.runtime_data = LlamaCppRuntimeData(client=client, info=info, model=model)
    _migrate_legacy_registry_entries(hass, entry)

    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    entry.async_on_unload(entry.add_update_listener(async_update_entry))

    return True


async def async_update_entry(hass: HomeAssistant, entry: LlamaCppConfigEntry) -> None:
    """Reload the entry when options or subentries change."""
    await hass.config_entries.async_reload(entry.entry_id)


async def async_unload_entry(hass: HomeAssistant, entry: LlamaCppConfigEntry) -> bool:
    """Unload a config entry."""
    return await hass.config_entries.async_unload_platforms(entry, PLATFORMS)
