"""Focused config-flow helper tests."""

from __future__ import annotations

from homeassistant.const import CONF_API_KEY, CONF_URL

from custom_components.llama_cpp_ai_task.config_flow import (
    CONF_REMOVE_API_KEY,
    _effective_reconfigure_api_key,
    _is_autogenerated_task_title,
    _reconfigure_defaults,
    _updated_reconfigure_data,
)


def test_reconfigure_defaults_do_not_echo_stored_api_key() -> None:
    """Stored credentials must never be suggested back to the browser."""
    entry_data = {
        CONF_URL: "http://server:8080",
        CONF_API_KEY: "secret",
        "future_key": "preserve-me",
    }

    assert _reconfigure_defaults(entry_data) == {CONF_URL: "http://server:8080"}
    assert CONF_API_KEY not in _reconfigure_defaults(entry_data)


def test_optional_api_key_reconfigure_preserves_replaces_and_removes() -> None:
    """Blank keeps a key, replacement updates it, and removal is explicit."""
    entry_data = {
        CONF_URL: "http://old:8080",
        CONF_API_KEY: "secret",
        "future_key": "preserve-me",
    }

    blank = {CONF_URL: "http://new:8080"}
    assert _effective_reconfigure_api_key(entry_data, blank) == "secret"
    assert _updated_reconfigure_data(
        entry_data, "http://new:8080", blank
    ) == {
        CONF_URL: "http://new:8080",
        CONF_API_KEY: "secret",
        "future_key": "preserve-me",
    }

    remove = {
        CONF_URL: "http://new:8080",
        CONF_REMOVE_API_KEY: True,
    }
    assert _effective_reconfigure_api_key(entry_data, remove) is None
    assert _updated_reconfigure_data(
        entry_data, "http://new:8080", remove
    ) == {
        CONF_URL: "http://new:8080",
        "future_key": "preserve-me",
    }

    replacement = {
        CONF_URL: "http://new:8080",
        CONF_API_KEY: "new-secret",
        CONF_REMOVE_API_KEY: True,
    }
    assert _effective_reconfigure_api_key(entry_data, replacement) == "new-secret"
    assert _updated_reconfigure_data(
        entry_data, "http://new:8080", replacement
    ) == {
        CONF_URL: "http://new:8080",
        CONF_API_KEY: "new-secret",
        "future_key": "preserve-me",
    }


def test_generic_router_title_remains_autogenerated_until_user_renames() -> None:
    """The generic router title must self-correct when a model is later selected."""
    assert _is_autogenerated_task_title("Llama.cpp", None) is True
    assert _is_autogenerated_task_title("llama.cpp AI Task", None) is True
    assert _is_autogenerated_task_title("Qwen3.5 4b", "qwen3.5-4b") is True
    assert _is_autogenerated_task_title("Kitchen classifier", None) is False
    assert _is_autogenerated_task_title("Kitchen classifier", "qwen3.5-4b") is False
